// DesignMyAvatar 配置

import {
  AvatarFaceFromTypeEnum,
  PromptToAvatarStyle,
  VIDEO_ASPECT_RATIO
} from '@/server/api/services/promptToAvatar/type';

// Gender 选项
export const GENDER_OPTIONS = [
  { value: 'female', label: 'Female' },
  { value: 'male', label: 'Male' }
] as const;

// Age 选项
export const AGE_OPTIONS = [
  { value: 'teenagers', label: 'Teenagers' },
  { value: 'young-adults', label: 'Young Adults' },
  { value: 'early-middle-aged', label: 'Early Middle-Aged Adults' },
  { value: 'middle-aged', label: 'Middle-aged Adults' },
  { value: 'elderly', label: 'Elderly' }
] as const;

// Country/Region 选项 - 民族/国籍形容词格式（与 aigc-web 保持一致）
export const COUNTRY_OPTIONS = [
  { value: 'Afghan', label: 'Afghan' },
  { value: 'Ålandic', label: 'Ålandic' },
  { value: 'Albanian', label: 'Albanian' },
  { value: 'Algerian', label: 'Algerian' },
  { value: 'American', label: 'American' },
  { value: 'American Samoan', label: 'American Samoan' },
  { value: 'Andorran', label: 'Andorran' },
  { value: 'Angolan', label: 'Angolan' },
  { value: 'Anguillan', label: 'Anguillan' },
  { value: 'Antarctic', label: 'Antarctic' },
  { value: 'Antiguan or Barbudan', label: 'Antiguan or Barbudan' },
  { value: 'Argentine / Argentinian', label: 'Argentine / Argentinian' },
  { value: 'Armenian', label: 'Armenian' },
  { value: 'Aruban', label: 'Aruban' },
  { value: 'Australian', label: 'Australian' },
  { value: 'Austrian', label: 'Austrian' },
  { value: 'Azerbaijani', label: 'Azerbaijani' },
  { value: 'Bahamian', label: 'Bahamian' },
  { value: 'Bahraini', label: 'Bahraini' },
  { value: 'Bangladeshi', label: 'Bangladeshi' },
  { value: 'Barbadian', label: 'Barbadian' },
  { value: 'Basotho', label: 'Basotho' },
  { value: 'Belarusian', label: 'Belarusian' },
  { value: 'Belgian', label: 'Belgian' },
  { value: 'Belizean', label: 'Belizean' },
  { value: 'Beninese', label: 'Beninese' },
  { value: 'Bermudian', label: 'Bermudian' },
  { value: 'Bhutanese', label: 'Bhutanese' },
  { value: 'Bissau-Guinean', label: 'Bissau-Guinean' },
  { value: 'Bolivian', label: 'Bolivian' },
  {
    value: 'Bonaire, Sint Eustatius and Saba Islander',
    label: 'Bonaire, Sint Eustatius and Saba Islander'
  },
  { value: 'Bosnian or Herzegovinian', label: 'Bosnian or Herzegovinian' },
  { value: 'Botswanan', label: 'Botswanan' },
  { value: 'Bouvet Islander', label: 'Bouvet Islander' },
  { value: 'Brazilian', label: 'Brazilian' },
  { value: 'British', label: 'British' },
  {
    value: 'British Indian Ocean Territory Islander',
    label: 'British Indian Ocean Territory Islander'
  },
  { value: 'British Virgin Islander', label: 'British Virgin Islander' },
  { value: 'Bruneian', label: 'Bruneian' },
  { value: 'Bulgarian', label: 'Bulgarian' },
  { value: 'Burkinabé', label: 'Burkinabé' },
  { value: 'Burmese', label: 'Burmese' },
  { value: 'Burundian', label: 'Burundian' },
  { value: 'Cabo Verdean', label: 'Cabo Verdean' },
  { value: 'Cambodian', label: 'Cambodian' },
  { value: 'Cameroonian', label: 'Cameroonian' },
  { value: 'Canadian', label: 'Canadian' },
  { value: 'Caymanian', label: 'Caymanian' },
  { value: 'Central African', label: 'Central African' },
  { value: 'Chadian', label: 'Chadian' },
  { value: 'Chilean', label: 'Chilean' },
  { value: 'Chinese', label: 'Chinese' },
  { value: 'Christmas Islander', label: 'Christmas Islander' },
  { value: 'Cocos Islander', label: 'Cocos Islander' },
  { value: 'Colombian', label: 'Colombian' },
  { value: 'Comorian', label: 'Comorian' },
  { value: 'Congolese', label: 'Congolese' },
  { value: 'Cook Islander', label: 'Cook Islander' },
  { value: 'Costa Rican', label: 'Costa Rican' },
  { value: 'Croatian', label: 'Croatian' },
  { value: 'Cuban', label: 'Cuban' },
  { value: 'Curaçaoan', label: 'Curaçaoan' },
  { value: 'Cypriot', label: 'Cypriot' },
  { value: 'Czech', label: 'Czech' },
  { value: 'Danish', label: 'Danish' },
  { value: 'Djiboutian', label: 'Djiboutian' },
  { value: 'Dominican', label: 'Dominican' },
  { value: 'Dutch', label: 'Dutch' },
  { value: 'Ecuadorian', label: 'Ecuadorian' },
  { value: 'Egyptian', label: 'Egyptian' },
  { value: 'Emirati', label: 'Emirati' },
  { value: 'Equatorial Guinean', label: 'Equatorial Guinean' },
  { value: 'Eritrean', label: 'Eritrean' },
  { value: 'Estonian', label: 'Estonian' },
  { value: 'Ethiopian', label: 'Ethiopian' },
  { value: 'Falkland Islander', label: 'Falkland Islander' },
  { value: 'Faroese', label: 'Faroese' },
  { value: 'Fijian', label: 'Fijian' },
  { value: 'Filipino', label: 'Filipino' },
  { value: 'Finnish', label: 'Finnish' },
  { value: 'French', label: 'French' },
  { value: 'French Guianese', label: 'French Guianese' },
  { value: 'French Polynesian', label: 'French Polynesian' },
  {
    value: 'French Southern Territories Islander',
    label: 'French Southern Territories Islander'
  },
  { value: 'Gabonese', label: 'Gabonese' },
  { value: 'Gambian', label: 'Gambian' },
  { value: 'Georgian', label: 'Georgian' },
  { value: 'German', label: 'German' },
  { value: 'Ghanaian', label: 'Ghanaian' },
  { value: 'Gibraltarian', label: 'Gibraltarian' },
  { value: 'Greek', label: 'Greek' },
  { value: 'Greenlandic', label: 'Greenlandic' },
  { value: 'Grenadian', label: 'Grenadian' },
  { value: 'Guadeloupean', label: 'Guadeloupean' },
  { value: 'Guamanian', label: 'Guamanian' },
  { value: 'Guatemalan', label: 'Guatemalan' },
  { value: 'Guernsey', label: 'Guernsey' },
  { value: 'Guinean', label: 'Guinean' },
  { value: 'Guyanese', label: 'Guyanese' },
  { value: 'Haitian', label: 'Haitian' },
  {
    value: 'Heard and McDonald Islander',
    label: 'Heard and McDonald Islander'
  },
  { value: 'Honduran', label: 'Honduran' },
  { value: 'Hong Kong Chinese', label: 'Hong Kong Chinese' },
  { value: 'Hungarian', label: 'Hungarian' },
  { value: 'Icelandic', label: 'Icelandic' },
  { value: 'I-Kiribati', label: 'I-Kiribati' },
  { value: 'Indian', label: 'Indian' },
  { value: 'Indonesian', label: 'Indonesian' },
  { value: 'Iranian', label: 'Iranian' },
  { value: 'Iraqi', label: 'Iraqi' },
  { value: 'Irish', label: 'Irish' },
  { value: 'Israeli', label: 'Israeli' },
  { value: 'Italian', label: 'Italian' },
  { value: 'Ivorian', label: 'Ivorian' },
  { value: 'Jamaican', label: 'Jamaican' },
  { value: 'Japanese', label: 'Japanese' },
  { value: 'Jersey', label: 'Jersey' },
  { value: 'Jordanian', label: 'Jordanian' },
  { value: 'Kazakhstani', label: 'Kazakhstani' },
  { value: 'Kenyan', label: 'Kenyan' },
  { value: 'Kittitian or Nevisian', label: 'Kittitian or Nevisian' },
  { value: 'Kuwaiti', label: 'Kuwaiti' },
  { value: 'Kyrgyzstani', label: 'Kyrgyzstani' },
  { value: 'Lao', label: 'Lao' },
  { value: 'Latvian', label: 'Latvian' },
  { value: 'Lebanese', label: 'Lebanese' },
  { value: 'Liberian', label: 'Liberian' },
  { value: 'Libyan', label: 'Libyan' },
  { value: 'Liechtensteiner', label: 'Liechtensteiner' },
  { value: 'Lithuanian', label: 'Lithuanian' },
  { value: 'Luxembourger', label: 'Luxembourger' },
  { value: 'Macanese', label: 'Macanese' },
  { value: 'Mahoran', label: 'Mahoran' },
  { value: 'Malagasy', label: 'Malagasy' },
  { value: 'Malawian', label: 'Malawian' },
  { value: 'Malaysian', label: 'Malaysian' },
  { value: 'Maldivian', label: 'Maldivian' },
  { value: 'Malian', label: 'Malian' },
  { value: 'Maltese', label: 'Maltese' },
  { value: 'Manx', label: 'Manx' },
  { value: 'Marshallese', label: 'Marshallese' },
  { value: 'Martiniquais', label: 'Martiniquais' },
  { value: 'Mauritanian', label: 'Mauritanian' },
  { value: 'Mauritian', label: 'Mauritian' },
  { value: 'Mexican', label: 'Mexican' },
  { value: 'Micronesian', label: 'Micronesian' },
  { value: 'Moldovan', label: 'Moldovan' },
  { value: 'Monegasque', label: 'Monegasque' },
  { value: 'Mongolian', label: 'Mongolian' },
  { value: 'Montenegrin', label: 'Montenegrin' },
  { value: 'Montserratian', label: 'Montserratian' },
  { value: 'Moroccan', label: 'Moroccan' },
  { value: 'Mozambican', label: 'Mozambican' },
  { value: 'Namibian', label: 'Namibian' },
  { value: 'Nauruan', label: 'Nauruan' },
  { value: 'Nepali', label: 'Nepali' },
  { value: 'New Caledonian', label: 'New Caledonian' },
  { value: 'New Zealander', label: 'New Zealander' },
  { value: 'Nicaraguan', label: 'Nicaraguan' },
  { value: 'Nigerian', label: 'Nigerian' },
  { value: 'Nigerien', label: 'Nigerien' },
  { value: 'Niuean', label: 'Niuean' },
  { value: 'Ni-Vanuatu', label: 'Ni-Vanuatu' },
  { value: 'Norfolk Islander', label: 'Norfolk Islander' },
  { value: 'North Korean', label: 'North Korean' },
  { value: 'North Macedonian', label: 'North Macedonian' },
  { value: 'Northern Mariana Islander', label: 'Northern Mariana Islander' },
  { value: 'Norwegian', label: 'Norwegian' },
  { value: 'Omani', label: 'Omani' },
  { value: 'Pakistani', label: 'Pakistani' },
  { value: 'Palauan', label: 'Palauan' },
  { value: 'Palestinian', label: 'Palestinian' },
  { value: 'Panamanian', label: 'Panamanian' },
  { value: 'Papua New Guinean', label: 'Papua New Guinean' },
  { value: 'Paraguayan', label: 'Paraguayan' },
  { value: 'Peruvian', label: 'Peruvian' },
  { value: 'Pitcairn Islander', label: 'Pitcairn Islander' },
  { value: 'Polish', label: 'Polish' },
  { value: 'Portuguese', label: 'Portuguese' },
  { value: 'Puerto Rican', label: 'Puerto Rican' },
  { value: 'Qatari', label: 'Qatari' },
  { value: 'Réunionese', label: 'Réunionese' },
  { value: 'Romanian', label: 'Romanian' },
  { value: 'Russian', label: 'Russian' },
  { value: 'Rwandan', label: 'Rwandan' },
  { value: 'Sahrawi', label: 'Sahrawi' },
  { value: 'Saint Barthélemy Islander', label: 'Saint Barthélemy Islander' },
  { value: 'Saint Helenian', label: 'Saint Helenian' },
  { value: 'Saint Lucian', label: 'Saint Lucian' },
  { value: 'Saint-Martinoise', label: 'Saint-Martinoise' },
  {
    value: 'Saint-Pierrais or Miquelonnais',
    label: 'Saint-Pierrais or Miquelonnais'
  },
  { value: 'Salvadoran', label: 'Salvadoran' },
  { value: 'Sammarinese', label: 'Sammarinese' },
  { value: 'Samoan', label: 'Samoan' },
  { value: 'São Toméan', label: 'São Toméan' },
  { value: 'Saudi', label: 'Saudi' },
  { value: 'Senegalese', label: 'Senegalese' },
  { value: 'Serbian', label: 'Serbian' },
  { value: 'Seychellois', label: 'Seychellois' },
  { value: 'Sierra Leonean', label: 'Sierra Leonean' },
  { value: 'Singaporean', label: 'Singaporean' },
  { value: 'Sint Maartener', label: 'Sint Maartener' },
  { value: 'Slovak', label: 'Slovak' },
  { value: 'Slovenian', label: 'Slovenian' },
  { value: 'Solomon Islander', label: 'Solomon Islander' },
  { value: 'Somali', label: 'Somali' },
  { value: 'South African', label: 'South African' },
  {
    value: 'South Georgian or South Sandwich Islander',
    label: 'South Georgian or South Sandwich Islander'
  },
  { value: 'South Korean', label: 'South Korean' },
  { value: 'South Sudanese', label: 'South Sudanese' },
  { value: 'Spanish', label: 'Spanish' },
  { value: 'Sri Lankan', label: 'Sri Lankan' },
  { value: 'Sudanese', label: 'Sudanese' },
  { value: 'Surinamese', label: 'Surinamese' },
  {
    value: 'Svalbardian or Jan Mayen Islander',
    label: 'Svalbardian or Jan Mayen Islander'
  },
  { value: 'Swazi', label: 'Swazi' },
  { value: 'Swedish', label: 'Swedish' },
  { value: 'Swiss', label: 'Swiss' },
  { value: 'Syrian', label: 'Syrian' },
  { value: 'Taiwanese', label: 'Taiwanese' },
  { value: 'Tajikistani', label: 'Tajikistani' },
  { value: 'Tanzanian', label: 'Tanzanian' },
  { value: 'Thai', label: 'Thai' },
  { value: 'Timorese', label: 'Timorese' },
  { value: 'Togolese', label: 'Togolese' },
  { value: 'Tokelauan', label: 'Tokelauan' },
  { value: 'Tongan', label: 'Tongan' },
  { value: 'Trinidadian or Tobagonian', label: 'Trinidadian or Tobagonian' },
  { value: 'Tunisian', label: 'Tunisian' },
  { value: 'Turkish', label: 'Turkish' },
  { value: 'Turkmen', label: 'Turkmen' },
  { value: 'Turks and Caicos Islander', label: 'Turks and Caicos Islander' },
  { value: 'Tuvaluan', label: 'Tuvaluan' },
  {
    value: 'U.S. Minor Outlying Islander',
    label: 'U.S. Minor Outlying Islander'
  },
  { value: 'U.S. Virgin Islander', label: 'U.S. Virgin Islander' },
  { value: 'Ugandan', label: 'Ugandan' },
  { value: 'Ukrainian', label: 'Ukrainian' },
  { value: 'Uruguayan', label: 'Uruguayan' },
  { value: 'Uzbekistani', label: 'Uzbekistani' },
  { value: 'Vatican', label: 'Vatican' },
  { value: 'Venezuelan', label: 'Venezuelan' },
  { value: 'Vietnamese', label: 'Vietnamese' },
  { value: 'Vincentian', label: 'Vincentian' },
  { value: 'Wallisian or Futunan', label: 'Wallisian or Futunan' },
  { value: 'Yemeni', label: 'Yemeni' },
  { value: 'Zambian', label: 'Zambian' },
  { value: 'Zimbabwean', label: 'Zimbabwean' }
] as const;

// Style 选项
export const STYLE_OPTIONS = [
  {
    value: PromptToAvatarStyle.Ugc,
    label: 'UGC',
    image:
      'https://d1735p3aqhycef.cloudfront.net/media/images/MtQKYOqpx0WlQqWl.webp'
  },
  {
    value: PromptToAvatarStyle.Pro,
    label: 'Pro',
    image:
      'https://d1735p3aqhycef.cloudfront.net/media/images/P03_Wfy5ZiOnA-MB.webp'
  }
] as const;

// Ratio 选项
export const RATIO_OPTIONS = [
  { value: VIDEO_ASPECT_RATIO.Vertical, label: '9:16' },
  { value: VIDEO_ASPECT_RATIO.Square, label: '1:1' },
  { value: VIDEO_ASPECT_RATIO.Horizontal, label: '16:9' }
] as const;

// 默认值
export const DEFAULT_VALUES = {
  faceSource: AvatarFaceFromTypeEnum.photo,
  gender: 'female',
  age: 'young-adults',
  country: 'American',
  style: PromptToAvatarStyle.Ugc,
  ratio: VIDEO_ASPECT_RATIO.Vertical,
  prompt: ''
};
